dist: trusty
sudo: false

language: c++

cache: 
  directories:
    - ${TRAVIS_BUILD_DIR}/cache-dir

jobs:
  include:
    - stage: Cache
      script: bash ${TRAVIS_BUILD_DIR}/prepare-cache.sh
      script: bash ${TRAVIS_BUILD_DIR}/prepare-cache.sh
    - stage: Test
      script: cat ${TRAVIS_BUILD_DIR}/cache-dir/test.txt
      script: cat ${TRAVIS_BUILD_DIR}/cache-dir/text.txt