dist: trusty
sudo: false

language: c++

cache: 
  directories:
    - ${TRAVIS_BUILD_DIR}/cache-dir

jobs:
  include:
    - stage: Build cache
      script: bash ${TRAVIS_BUILD_DIR}/prepare-cache.sh
    - stage: Test
      script: ls ${TRAVIS_BUILD_DIR}/cache-dir
    - stage: Test
      script: ls ${TRAVIS_BUILD_DIR}/cache-dir