dist: trusty
sudo: false

language: c++

cache: 
  directories:
    - ${TRAVIS_BUILD_DIR}/cache-dir

jobs:
  include:
    - stage: Prepare Cache
      script: bash ${TRAVIS_BUILD_DIR}/prepare-cache.sh
    - stage: Prepare Cache
      script: bash ${TRAVIS_BUILD_DIR}/prepare-cache.sh
    - stage: Test
      script: bash ${TRAVIS_BUILD_DIR}/test-cache.sh
    - stage: Test
      script: bash ${TRAVIS_BUILD_DIR}/test-cache.sh